{
 "title": "WebSocket HashIO",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Rate Limiter Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "HBar Rate Limiter Counter For Transactions in the eth_sendRawTransaction flow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rpc_relay_hbar_rate_limit{container=\"hedera-json-rpc-relay\", methodName=\"eth_sendRawTransaction\", namespace=\"$namespace\"})/2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HBar Rate Limiter Remaining Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rpc_relay_hbar_rate_remaining{container=\"hedera-json-rpc-relay\", namespace=\"$namespace\"}) / 2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HBar Rate Limiter Counter for Queries in the eth_getCode flow ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rpc_relay_hbar_rate_limit{container=\"hedera-json-rpc-relay\", methodName=\"eth_getCode\", mode=\"QUERY\", namespace=\"$namespace\"})/2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage - Hbar Account and Burn Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Relay Operator Balance (ℏ)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(accountId)  (rpc_relay_operator_balance{namespace=\"$namespace\", mode!=\"QUERY\", mode!=\"TRANSACTION\"} / 100000000)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Operator account burn rate (ℏ)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_consensusnode_response_sum{namespace=\"$namespace\"}[$__range])) / -100000000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Hbar Spent per Day over the last Month By Mode - Regenerated",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[1d])) by(mode) / 100000000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HBar Rate Limiter Counter for Transactions in the eth_sendRawTransaction flow",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(rpc_relay_hbar_rate_limit{container=\"hedera-json-rpc-relay\", methodName=\"eth_sendRawTransaction\", mode=\"TRANSACTION\", namespace=\"$namespace\"})/2",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay Operator Balance Burn Rate over 1 day(ℏ)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "abs(delta(hedera_account_balance{account_id=\"0.0.995584\", network=\"$namespace\"}[1d]) / 100000000)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Operator Cost  (ℏ) by Mode",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (mode)(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[$__range])) / -100000000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Consensus Node (txns) Calls by Mode",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 5, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (mode)(increase(rpc_relay_consensusnode_response_count{ namespace=\"$namespace\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay Operator Balance (ℏ)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "avg_over_time(rpc_relay_operator_balance{ namespace=\"$namespace\", mode!=\"QUERY\", mode!=\"TRANSACTION\"}[$__interval]) / 100000000",
       "legendFormat": "{{accountId}}"
      }
     ]
    },
    {
     "title": "Consensus Node Cost Rate by Call (ℏ)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum by(caller) (rate(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[$__rate_interval])) / 100000000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Consensus Node Cost by Call (ℏ)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10,sum by(caller) (increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[$__range])) / 100000000)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Consensus Node Volume by Call ",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10,sum by(caller) (increase(rpc_relay_consensusnode_response_count{ namespace=\"$namespace\"}[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Hbar Spent By type",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[1d])) by(type) / 100000000",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "Hbar Spent By Mode",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 5, "x": 6, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[$__range])) by(mode) / 100000000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Hbar Spent By caller",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[$__range])) by(caller) / 100000000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HBar spend on FileAppendTransaction",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_consensusnode_response_bucket{mode=\"TRANSACTION\", type=\"FileAppendTransaction\", status=\"SUCCESS\", caller=\"eth_sendRawTransaction\"}[5m])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Hbar Spent per Day over the last Month By Mode",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[1d])) by(mode) / 100000000",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "Hbar Spent per Day over the last Month By Mode V2",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "avg(delta(rpc_relay_operator_balance{namespace=\"$namespace\", mode!=\"QUERY\", mode!=\"TRANSACTION\"}[1d])) by (accountId) / -100000000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Hbar Spent per Day over the last day By Mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[30m])) by(mode) / 100000000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Hbar Spent per minute",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[$__rate_interval])) by (pod) / 100000000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Hbar Spent per Day over the last Month by MethodName",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[1d])) by(caller) / 100000000",
       "legendFormat": "{{methodName}}"
      }
     ]
    },
    {
     "title": "Hbar Spent per Day over the last Month by Type",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 103 },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_consensusnode_response_sum{ namespace=\"$namespace\"}[1d])) by(type) / 100000000",
       "legendFormat": "{{methodName}}"
      }
     ]
    },
    {
     "title": "Consensus Node Calls by AccountId/EvmAddress",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 112 },
     "targets": [
      {
       "expr": "topk(10,sum by(interactingEntity)(increase(rpc_relay_consensusnode_response_count{namespace=\"$namespace\", interactingEntity!=\"\"}[$__range])))",
       "legendFormat": "{{interactingEntity}}"
      }
     ]
    },
    {
     "title": "Hbar Spent by AccountId/EvmAddress",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 121 },
     "targets": [
      {
       "expr": "topk(10,sum by(interactingEntity)(increase(rpc_relay_consensusnode_response_sum{namespace=\"$namespace\", interactingEntity!=\"\"}[$__range])) / 100000000)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Volume, RPS, Latency, Limits - API Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Rate (RPS)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Rate (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 14, "x": 5, "y": 2 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Relay RPS"
      },
      {
       "expr": "sum(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Mirror Node RPS"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failure Request Rate",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 5, "y": 9 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", statusCode!=\"200\", statusCode!=\"400\"}[1m]))",
       "legendFormat": "Failed Request RPS"
      }
     ]
    },
    {
     "title": "Failure %",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\", statusCode!=\"400\"}[$__range]))/sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failure Total Count",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 21, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\", statusCode!=\"400\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "eth_call Failure Request Rate",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\", statusCode!=\"400\", method=\"eth_call\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "eth_call Failed Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 5, "y": 16 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", statusCode!=\"200\", statusCode!=\"400\"}[1m]))",
       "legendFormat": "Failed Request RPS"
      }
     ]
    },
    {
     "title": "eth_call Failure %",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 18, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\", statusCode!=\"400\",method=\"eth_call\"}[$__range]))/sum(increase(rpc_relay_method_response_count{namespace=\"$namespace\", method=\"eth_call\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "eth_call Failure Total Count",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 21, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\", statusCode!=\"400\", method=\"eth_call\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "eth_sendRawTransaction Failure Request Rate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\", method=\"eth_sendRawTransaction\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "eth_sendRawTransaction Failed Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 5, "y": 23 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", statusCode!=\"200\",method=\"eth_sendRawTransaction\"}[1m]))",
       "legendFormat": "Failed Request RPS"
      }
     ]
    },
    {
     "title": "eth_sendRawTransaction Failure %",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 18, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\",method=\"eth_sendRawTransaction\"}[$__range]))/sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\", method=\"eth_sendRawTransaction\" }[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "eth_sendRawTransaction Failure Total Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 21, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\", method=\"eth_sendRawTransaction\"}[$__range])) by (namespace)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "IP Rate Limiter by Method",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "sum by(methodName)(rpc_relay_ip_rate_limit{ namespace=\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Hbar Rate Limiter by Method",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_hbar_rate_limit{ namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg. Latency (ms)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 153 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg (rate(rpc_relay_method_response_sum{ namespace=\"$namespace\"}[1m])) / avg (rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Relay"
      },
      {
       "expr": "avg(rate(rpc_relay_mirror_response_sum{ namespace=\"$namespace\"}[1m]))/avg(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Mirror Node"
      }
     ]
    },
    {
     "title": "Avg. Latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 19, "x": 5, "y": 153 },
     "targets": [
      {
       "expr": "avg (rate(rpc_relay_method_response_sum{ namespace=\"$namespace\"}[1m])) / avg (rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Relay"
      },
      {
       "expr": "avg(rate(rpc_relay_mirror_response_sum{ namespace=\"$namespace\"}[1m]))/avg(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Mirror Node"
      }
     ]
    },
    {
     "title": "Latest Requests (RPS)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Relay"
      },
      {
       "expr": "sum(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Mirror Node"
      }
     ]
    },
    {
     "title": "Requests (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 19, "x": 5, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Relay"
      },
      {
       "expr": "sum(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "Mirror Node"
      }
     ]
    }
   ]
  },
  {
   "title": "Relay Details - Volume, RPS, Usage and Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg. Latency (ms)",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 185 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(rate(rpc_relay_method_response_sum{namespace=\"$namespace\"}[1m]))/avg(rate(rpc_relay_method_response_count{namespace=\"$namespace\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay Avg. Latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 19, "x": 5, "y": 185 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(rate(rpc_relay_method_response_sum{namespace=\"$namespace\"}[$__rate_interval]))/avg(rate(rpc_relay_method_response_count{namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Avg. Latency"
      }
     ]
    },
    {
     "title": "Relay Response Latency (ms) by Path",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 192 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk(6,sum by (method) (rate(rpc_relay_method_response_sum{ namespace=\"$namespace\"}[1m])) / sum by (method) (rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[1m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Requests (RPS)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 201 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Requests (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 14, "x": 5, "y": 201 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Requests Cummulative (Units)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 201 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Requests (RPS) by Method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 208 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__rate_interval])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Timeout Requests (RPS)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 216 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[$__rate_interval]) - ignoring(le) rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"30000\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Requests Above 30s - Timeout",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 4, "y": 216 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[$__rate_interval]) - ignoring(le) rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"30000\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Timeout Requests %",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 216 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[$__range]) - ignoring(le) increase(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"30000\"}[$__range])) / sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Timeout Requests Cummulative (Units)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 216 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[$__range]) - ignoring(le) increase(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"30000\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - 60s latency Requests (RPS)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 224 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[$__rate_interval]) - ignoring(le) rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"60000\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Requests Above 60s - Timeout",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 4, "y": 224 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[$__rate_interval]) - ignoring(le) rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"60000\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - 60s Latency Requests %",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 224 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[$__range]) - ignoring(le) increase(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"60000\"}[$__range])) / sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - 60s Latency Requests Cummulative (Units)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 224 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[$__range]) - ignoring(le) increase(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"60000\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed Relay Requests By Status and Method (Units)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 232 },
     "targets": [
      {
       "expr": "sum(increase(rpc_relay_method_response_count{ namespace=\"$namespace\", statusCode!=\"200\"}[$__range])) by (statusCode, method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Requests By Pod (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 241 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__rate_interval]))by(pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Requests Amount (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 250 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_count{ namespace=\"$namespace\"}[$__rate_interval])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Requests below 5s Latency (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 259 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk(6,sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"5000\"}[$__rate_interval])) by (method))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Requests above 5s Latency (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 259 },
     "targets": [
      {
       "expr": "topk(6,sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[1m]) - ignoring(le) rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"5000\"}[1m])) by (method))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Requests between 5s and 10s Latency (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 268 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"10000\"}[1m]) - ignoring(le) rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"5000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay - Requests above 10s Latency (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 268 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[1m]) - ignoring(le) rate(rpc_relay_method_response_bucket{ namespace=\"$namespace\", le=\"10000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests to API by MethodName",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 278 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(15,  sum by(method)(increase(rpc_relay_method_response_count{namespace=\"$namespace\"}[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed Requests to API by MethodName",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 278 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(method)(increase(rpc_relay_method_response_count{namespace=\"$namespace\",statusCode!=\"200\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Relay Requests by Status Code (excluding 200)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 287 },
     "targets": [
      {
       "expr": "sum by(statusCode)(increase(rpc_relay_method_response_count{namespace=\"$namespace\",statusCode!=\"200\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests by Path (units) - Per day over the month",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 296 },
     "targets": [
      {
       "expr": "topk(15,sum by(method)(increase(rpc_relay_method_response_count{namespace=\"$namespace\"}[1d])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cumulative Requests by Path (units)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 306 },
     "targets": [
      {
       "expr": "sum by(method)(increase(rpc_relay_method_response_count{namespace=\"$namespace\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cache  Size By Pod",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 316 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rpc_relay_cache{method=\"\", key=\"\",  namespace=\"$namespace\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cache Hits by Method",
     "type": "timeseries",
     "description": "Amount of Cache Hits (Found and returned)",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 316 },
     "targets": [
      {
       "expr": "sum(increase(rpc_cache_service_methods_counter{ namespace=\"$namespace\"}[$__range])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Relay - Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latest Error Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 417 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", app=~\".*-hashio\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Mirror Node Details - Volume, RPS, Usage and Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg. Latency (ms)",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 418 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(rate(rpc_relay_mirror_response_sum{ namespace=\"$namespace\"}[1m]))/avg(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror  Node Avg. Latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 19, "x": 4, "y": 418 },
     "targets": [
      {
       "expr": "avg(rate(rpc_relay_mirror_response_sum{ namespace=\"$namespace\"}[1m]))/avg(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m]))   ",
       "legendFormat": "Mirror Node Avg. Latency"
      }
     ]
    },
    {
     "title": "Mirror Node Latency by Path",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 423 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_sum{ namespace=\"$namespace\"}[1m])) by (method) /\nsum(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Percentile 90 - Expected Latency for Mirror Node by Method",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 432 },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\"}[1m])) by (le, method))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Percentile 95 - Expected Latency for Mirror Node by Method",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 441 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\"}[1m])) by (le, method))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node RPS",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 450 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 19, "x": 5, "y": 450 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node RPS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 458 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__rate_interval])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node - Requests below 1s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 467 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"1000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node - Requests between 1s and 5s  Latency (Units)anel Title",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 467 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"5000\"}[1m]) - ignoring(le) rate(rpc_relay_mirror_response_bucket{namespace=\"$namespace\", le=\"1000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node - Requests between 5s and 10s Latency (Units)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 475 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"10000\"}[1m]) - ignoring(le) rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"5000\"}[1m])) by (method)  ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node - Requests between 10s and 20s Latency (Units)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 475 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"20000\"}[1m]) - ignoring(le) rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"10000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node - Requests between 20s and 30s Latency (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 483 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"30000\"}[1m]) - ignoring(le) rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"20000\"}[1m])) by (method) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node - Requests above 30s Latency (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 483 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"+Inf\"}[1m]) - ignoring(le) rate(rpc_relay_mirror_response_bucket{ namespace=\"$namespace\", le=\"30000\"}[1m])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Response by Status & Type (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 491 },
     "targets": [
      {
       "expr": "topk by(statusCode) (5, sum by(statusCode, method) (rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node RPS by Path",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 501 },
     "targets": [
      {
       "expr": "sum(rate(rpc_relay_mirror_response_count{namespace=~\"$namespace\"}[$__rate_interval])) by (method)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node Contract/Call Calls by StatusCode (Units)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 510 },
     "targets": [
      {
       "expr": "sum by(statusCode) (increase(rpc_relay_mirror_response_count{ namespace=\"$namespace\", method=\"contracts/call\"}[$__rate_interval]))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Mirror Node Contract/Call Calls by StatusCode (%)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 510 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(statusCode) (increase(rpc_relay_mirror_response_count{ namespace=\"$namespace\", method=\"contracts/call\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node Contract/Call Calls by StatusCode (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 518 },
     "targets": [
      {
       "expr": "rpc_relay_mirror_response_count{namespace=\"$namespace\", method=\"contracts/call\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mirror Node Contract/Call Calls by StatusCode (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 526 },
     "targets": [
      {
       "expr": "topk by(statusCode) (10, sum by(statusCode) (rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\", method=\"contracts/call\"}[$__rate_interval])))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Mirror Node Calls by StatusCode (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 536 },
     "targets": [
      {
       "expr": "topk by(statusCode) (10, sum by(statusCode) (rate(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Mirror Node Calls by Method",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 546 },
     "targets": [
      {
       "expr": "sum by(method)(increase(rpc_relay_mirror_response_count{ namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Query Response by Status & Type (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 556 },
     "targets": [
      {
       "expr": "topk by(status) (10, sum by(status, type) (rate(rpc_relay_consensusnode_response_count{ namespace=\"$namespace\", mode=\"QUERY\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transaction Response by Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 564 },
     "targets": [
      {
       "expr": "topk by(status) (10, sum by(status) (rate(rpc_relay_consensusnode_response_count{ namespace=\"$namespace\", mode=\"TRANSACTION\", type=\"EthereumTransaction\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "WebSockets System Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "WebSocket Active Connections",
     "type": "timeseries",
     "description": "The number of active web socket connections.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 419 },
     "targets": [
      {
       "expr": "sum(rpc_websocket_active_connections{namespace=\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "WebSocket Active NewHeads Polls",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 419 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rpc_websocket_active_newheads_polls{namespace=\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "WebSocket Method Counter",
     "type": "piechart",
     "description": "WebSocket Method Counter",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 427 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(15,  sum by(method)(increase(rpc_websocket_method_counter{namespace=\"$namespace\"}[$__range])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "WebSocket Subscription Times",
     "type": "histogram",
     "description": "WebSocket Subscription Times",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 427 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rpc_websocket_subscription_times_bucket{namespace=\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "WebSocket Message Duration",
     "type": "histogram",
     "description": "WebSocket Message Duration in miliseconds",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 435 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rpc_websocket_message_duration_miliseconds_bucket{namespace=\"$namespace\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "WebSocket Messages Received Total",
     "type": "stat",
     "description": "WebSocket Messages Received Total",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 435 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rpc_websocket_messages_received_total{namespace=\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "WebSocket Connections Established Total",
     "type": "stat",
     "description": "WebSocket Connections Established Total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 443 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rpc_websocket_connections_established_total{namespace=\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Websocket Connections",
     "type": "gauge",
     "description": "Active WebSocket Connections",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 443 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rpc_websocket_active_connections{namespace=\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Websocket Connections Closed Total",
     "type": "stat",
     "description": "Websocket Connections Closed Total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 451 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rpc_websocket_connections_closed_total{namespace=\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Connections per IP",
     "type": "gauge",
     "description": "Active Connections per IP",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 451 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rpc_websocket_active_connections_per_ip)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "WebSocket Total Connection Limit Enforced",
     "type": "timeseries",
     "description": "WebSocket Total Connection Limit Enforced",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 459 },
     "targets": [
      {
       "expr": "sum(rpc_websocket_total_connection_limit_enforced)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "WebSocket CPU Usage",
     "type": "gauge",
     "description": "WebSocket Server CPU usage",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 420 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(rpc_relay_process_cpu_seconds_total{namespace=\"$namespace\"}[5m]) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "WebSocket Active Connections Per IP",
     "type": "gauge",
     "description": "WebSocket Active Connections Per IP",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 420 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rpc_websocket_active_connections_per_ip)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "WebSocket Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 428 },
     "targets": [
      {
       "expr": "rpc_relay_process_resident_memory_bytes{namespace=\"$namespace\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Consensus Node Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consensus Node Calls by Status (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 190 },
     "targets": [
      {
       "expr": "topk by(status) (10, sum by(status) (rate(rpc_relay_consensusnode_response_count{ namespace=\"$namespace\"}[$__rate_interval])))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Query Response by Status & Type (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
     "targets": [
      {
       "expr": "topk by(status) (10, sum by(status, type) (rate(rpc_relay_consensusnode_response_count{ namespace=\"$namespace\", mode=\"QUERY\"}[$__rate_interval])))",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Transaction Response by Status",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 210 },
     "targets": [
      {
       "expr": "topk by(status) (10, sum by(status) (rate(rpc_relay_consensusnode_response_count{ namespace=\"$namespace\", mode=\"TRANSACTION\", type=\"EthereumTransaction\"}[$__rate_interval])))",
       "legendFormat": "{{ method }}"
      }
     ]
    }
   ]
  }
 ]
}