version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/*"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 1
      include:
        - "*"
    groups:
      minor-and-patch-npm-daily:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directories: 
      - "/dapp-example"
      - "/docs/examples"
      - "/k6"
      - "/tools/hardhat-example"
      - "/tools/hardhat-viem-example"
      - "/tools/solidity-coverage-example"
      - "/tools/subgraph-example"
      - "/tools/waffle-example"
      - "/tools/wagmi-example"
      - "/tools/web3js-example"
      - "/tools/whbar-hardhat-example"
      - "/tools/hedera-crosschain-bridge"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      minor-and-patch-npm-weekly:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "gomod"
    directories: 
      - "/tools/golang-example"
      - "/tools/golang-json-rpc-tests"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      minor-and-patch-gomod-weekly:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "cargo"
    directories: 
      - "/tools/alloy-core-rs-example"
      - "/tools/ethers-rs-example"
      - "/tools/web3rs-example"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      minor-and-patch-cargo-weekly:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      minor-and-patch-actions-weekly:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    
  - package-ecosystem: "docker"
    directories: 
      - "/"
      - "/tools/whbar-hardhat-example"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      minor-and-patch-docker-weekly:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
