# Always comment on PRs
comment:
  layout: "diff, flags, files"
  behavior: new # deletes old comment and posts a new one
  require_changes: true

coverage:
  status:
    patch:
      default:
        target: 80%
        threshold: 1%
    project:
      default:
        target: 80%
        threshold: 1%

ignore:
  - "packages/*/dist"
