// SPDX-License-Identifier: Apache-2.0

/**
 * This list is used only for building test mocks;
 * relay.rpcMethodRegistry is the source of truth
 */
const REGISTRY_METHODS = [
  'eth_accounts',
  'eth_blockNumber',
  'eth_call',
  'eth_chainId',
  'eth_estimateGas',
  'eth_feeHistory',
  'eth_gasPrice',
  'eth_getBalance',
  'eth_getBlockByHash',
  'eth_getBlockByNumber',
  'eth_getBlockReceipts',
  'eth_getBlockTransactionCountByHash',
  'eth_getBlockTransactionCountByNumber',
  'eth_getCode',
  'eth_getFilterChanges',
  'eth_getFilterLogs',
  'eth_getLogs',
  'eth_getStorageAt',
  'eth_getTransactionByBlockHashAndIndex',
  'eth_getTransactionByBlockNumberAndIndex',
  'eth_getTransactionByHash',
  'eth_getTransactionCount',
  'eth_getTransactionReceipt',
  'eth_getUncleByBlockHashAndIndex',
  'eth_getUncleByBlockNumberAndIndex',
  'eth_getUncleCountByBlockHash',
  'eth_getUncleCountByBlockNumber',
  'eth_hashrate',
  'eth_maxPriorityFeePerGas',
  'eth_mining',
  'eth_newBlockFilter',
  'eth_newFilter',
  'eth_newPendingTransactionFilter',
  'eth_sendRawTransaction',
  'eth_syncing',
  'eth_uninstallFilter',
  'net_listening',
  'net_version',
  'web3_clientVersion',
  'web3_sha3',
  'admin_config',
  'debug_getBadBlocks',
  'debug_getRawBlock',
  'debug_getRawHeader',
  'debug_getRawReceipts',
  'debug_getRawTransaction',
  'debug_traceBlockByHash',
  'debug_traceBlockByNumber',
  'debug_traceTransaction',
  'txpool_content',
  'txpool_contentFrom',
  'txpool_status',
];

export const RPC_METHODS = {
  REGISTRY_METHODS,
  UNSUPPORTED_METHODS: [
    'eth_coinbase',
    'eth_blobBaseFee',
    'eth_getProof',
    'eth_createAccessList',
    'eth_sendTransaction',
    'eth_sign',
    'eth_signTransaction',
    'eth_simulateV1',
    'eth_signTypedData',
    'eth_getWork',
    'eth_protocolVersion',
    'eth_submitHashrate',
    'net_peerCount',
    'trace_block',
    'trace_blockByNumber',
    'trace_transaction',
  ],
};
