# Default values for json-rpc-relay.
affinity: {}

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# For reference see .env.ws.example
config:
  # ========== REQUIRED CONFIGURATION ==========
  # Network Configuration
  CHAIN_ID: ''
  HEDERA_NETWORK: ''
  MIRROR_NODE_URL: ''

  # Operator Account (Required for transaction execution)
  # OPERATOR_ID_MAIN:
  # OPERATOR_KEY_MAIN:
  # OPERATOR_KEY_FORMAT:

  # WebSocket Configuration
  SUBSCRIPTIONS_ENABLED: true

  # ========== WEBSOCKET SERVER SETTINGS ==========
  # WEB_SOCKET_PORT:
  # WEB_SOCKET_HTTP_PORT:
  # WS_CONNECTION_LIMIT:
  # WS_CONNECTION_LIMIT_PER_IP:
  # WS_MAX_INACTIVITY_TTL:
  # WS_PING_INTERVAL:

  # ========== SUBSCRIPTION CONFIGURATION ==========
  # WS_SUBSCRIPTION_LIMIT:
  # WS_MULTIPLE_ADDRESSES_ENABLED:
  # WS_NEW_HEADS_ENABLED:
  # WS_SAME_SUB_FOR_SAME_EVENT:
  # WS_POLLING_INTERVAL:
  # WS_RELAY_URL:

  # ========== CACHE & BATCH CONFIGURATION ==========
  # WS_CACHE_TTL:
  # WS_BATCH_REQUESTS_ENABLED:
  # WS_BATCH_REQUESTS_MAX_SIZE:

  # ========== MIRROR NODE CONFIGURATION ==========
  # MIRROR_NODE_RETRIES:
  # MIRROR_NODE_RETRY_DELAY:
  # MIRROR_NODE_TIMEOUT:
  # MIRROR_NODE_LIMIT_PARAM:
  # MIRROR_NODE_URL_HEADER_X_API_KEY:
  # MIRROR_NODE_URL_WEB3:
  # MIRROR_NODE_AGENT_CACHEABLE_DNS:

  # ========== ETH CALL CONFIGURATION ==========
  # ETH_CALL_DEFAULT_TO_CONSENSUS_NODE:
  # CONSENSUS_MAX_EXECUTION_TIME:
  # SDK_REQUEST_TIMEOUT:
  # CONTRACT_QUERY_TIMEOUT_RETRIES:

  # ========== REDIS CONFIGURATION ==========
  REDIS_ENABLED: false
  # REDIS_URL:
  # REDIS_RECONNECT_DELAY_MS:
  # MULTI_SET:

  # ========== OTHER SETTINGS ==========
  # CLIENT_TRANSPORT_SECURITY:
  # USE_ASYNC_TX_PROCESSING:
  # DEV_MODE:
  # LOG_LEVEL: 'trace'

# -- Extra environment variables from existing secrets or configmaps
extraEnvFrom: []
# - secretRef:
#     name: '{{ .Release.Name }}-env'

fullnameOverride: ''

global:
  namespaceOverride: ''

image:
  pullPolicy: IfNotPresent
  registry: ghcr.io
  repository: hiero-ledger/hiero-json-rpc-relay
  # Overrides the image tag whose default is the chart appVersion.
  tag: ''

imagePullSecrets: []

ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

livenessProbe:
  failureThreshold: 5
  httpGet:
    path: /health/liveness
    port: metrics
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5

nameOverride: ''

nodeSelector: {}

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

ports:
  - name: websocket
    containerPort: 8546
  - name: metrics # port for http endpoints (metrics and health)
    containerPort: 8547

replicaCount: 2

resources:
  limits:
    cpu: 1100m
    memory: 700Mi
  requests:
    cpu: 1100m
    memory: 350Mi

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: false

service:
  annotations: {}
  port: 8546
  type: ClusterIP

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ''

tolerations: []

readinessProbe:
  failureThreshold: 5
  httpGet:
    path: /health/readiness
    port: metrics
  initialDelaySeconds: 20
  timeoutSeconds: 5

terminationGracePeriodSeconds: 60

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 10%
    maxUnavailable: 25%
