apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "json-rpc-relay-ws.fullname" . }}
  labels:
    app:  {{ template "json-rpc-relay-ws.name" . }}
    {{ include "json-rpc-relay-ws.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
    {{- if eq $key "HEDERA_NETWORK" }}
      {{ $key }}: {{ if typeIs "string" $value}} {{ $value | lower | quote }} {{else}} {{ printf "{%s}" (tpl (join "," $value | trimPrefix "[" | trimSuffix "]") $) | squote }} {{end}}
    {{- else }}
      {{ $key }}: {{ if typeIs "float64" $value }}{{ $value | int64 | quote }}{{ else }}{{ $value | quote }}{{ end }}
    {{- end }}
  {{- end }}
  {{- include "json-rpc-relay-ws.redis-config" . | nindent 2 }}
