name: Dapp Tests

on:
  pull_request:
    branches: [main, release/**]
  push:
    branches: [main, release/**]
    tags: [v*]

concurrency:
  group: pr-checks-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  setup-local-hedera:
    name: Dapp Tests
    runs-on: hiero-smart-contracts-linux-medium
    timeout-minutes: 45 # Set to 45 minutes for now
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y make gcc g++

      - name: Install packages
        run: npm ci

      - name: Create .env file
        run: |
          cp ./dapp-example/localDappCI.env ./dapp-example/.env
          cp ./tests/server/localAcceptance.env .env

      - name: Build Typescript
        run: npm run build

      - name: Generate falcon-values config file
        run: |
          cat > .github/falcon.yml <<EOF
          network:
            --release-tag: "v0.72.0"
            --node-aliases: "node1"
          setup:
            --release-tag: "v0.72.0"
            --node-aliases: "node1"
          consensusNode:
            --node-aliases: "node1"
          mirrorNode:
            --enable-ingress: true
            --pinger: true
            --mirror-node-version: "v0.151.0"
            --values-file: .github/mirror-node-values.yaml
          EOF

      - name: Setup Kind
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
        with:
          install_only: true
          node_image: kindest/node:v1.32.5@sha256:e3b2327e3a5ab8c76f5ece68936e4cafaa82edf58486b769727ab0b3b97a5b0d
          version: v0.29.0
          kubectl_version: v1.32.5
          verbosity: 3
          wait: 120s

      - name: Start the solo node
        run: |
          npx @hashgraph/solo@0.68.0 one-shot falcon deploy \
            --values-file .github/falcon.yml \
            --dev \
            --deploy-explorer=false \
            --deploy-relay=false
        timeout-minutes: 15

      - name: Forward solo ports
        run: .github/scripts/forward-ports.sh

      - name: Start Redis
        run: docker run -d --name redis -p 6379:6379 redis:7-alpine

      - name: Start the local relay
        run: npm run start &

      - name: Build, Bootstrap & Test the dapp in Docker
        run: docker compose up --exit-code-from synpress
        working-directory: ./dapp-example/

      - name: Dump relay logs
        if: ${{ always() && !cancelled() }}
        uses: step-security/gh-docker-logs@2ffe2e0e1da43c5db68902dd900c47cdba10bfe6 # v2.2.6
        with:
          dest: './logs'

      - name: Tar logs
        if: ${{ always() && !cancelled() }}
        run: tar cvzf ./logs.tgz ./logs

      - name: Upload logs to GitHub
        if: ${{ always() && !cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: logs.tgz
          path: ./logs.tgz

      - name: Publish Reports
        uses: mikepenz/action-junit-report@bccf2e31636835cf0874589931c4116687171386 # v6.4.0
        if: ${{ always() && !cancelled() }}
        with:
          check_name: Dapp Test Report
          report_paths: "**/*.xml"
          detailed_summary: true
