name: Reusable dev tool workflow

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
      directory:
        required: true
        type: string

permissions:
  contents: read

jobs:
  dev-tool-workflow:
    runs-on: hiero-smart-contracts-linux-medium
    permissions:
      contents: write
      actions: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y make gcc g++

      - name: Setup node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 22

      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: "1.24.0"

      - name: Install packages
        run: npm ci

      - name: Create .env file
        run: |
          cp ${{ inputs.directory }}/.env.example ${{ inputs.directory }}/.env
          cp ./tests/server/localAcceptance.env .env

      - name: Build Typescript
        run: npm run build

      - name: Setup Kind
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        with:
          install_only: true
          node_image: kindest/node:v1.32.5@sha256:e3b2327e3a5ab8c76f5ece68936e4cafaa82edf58486b769727ab0b3b97a5b0d
          version: v0.29.0
          kubectl_version: v1.32.5
          verbosity: 3
          wait: 120s

      - name: Start the solo node
        run: |
          npx @hashgraph/solo@${{ inputs.soloVersion || '0.68.0' }} one-shot falcon deploy \
            --values-file .github/falcon.yml \
            --dev \
            --force-port-forward \
            --deploy-relay=false
        timeout-minutes: 15

      - name: Forward solo ports
        run: .github/scripts/forward-ports.sh

      - name: Start Redis
        run: docker run -d --name redis -p 6379:6379 redis:7-alpine

      - name: Start the local relay http server
        run: npm run start &

      - name: Start the local relay ws server
        run: npm run start:ws &

      - name: Install dependencies
        run: cd ${{ inputs.directory }}/ && npm ci

      - name: Run the tests
        run: ${{ inputs.command }}
