name: Foundry tool test

on: workflow_dispatch

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    defaults:
      run:
        working-directory: ./tools/foundry-example/
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: hiero-smart-contracts-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout Repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: step-security/foundry-toolchain@1e2de7031ae7e05d5e9ad79202047df62d77955a # v1.8.0
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
