name: Foundry tool test

on: workflow_dispatch

env:
  FOUNDRY_PROFILE: ci

permissions:
  contents: read

jobs:
  check:
    defaults:
      run:
        working-directory: ./tools/foundry-example/
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: hiero-smart-contracts-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: step-security/foundry-toolchain@52c5ff6279374143a2a36c326a723f9bd3555836 # v1.7.1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
